const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
function icon(name) {
  const paths = {
    chart: '<path d="M4 17l5-5 4 3 7-9M14 6h6v6"/>',
    grid: '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    history: '<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6M12 7v5l3 2"/>',
    settings: '<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2" fill="var(--surface)"/><circle cx="15" cy="12" r="2" fill="var(--surface)"/><circle cx="8" cy="18" r="2" fill="var(--surface)"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    download: '<path d="M12 3v12m-4-4 4 4 4-4M4 16v4h16v-4"/>',
    sparkles: '<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>'
  };
  return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${paths[name] || paths.chart}</svg>`;
}
$$('[data-icon]').forEach(el => { el.innerHTML = icon(el.dataset.icon); });
const stocks = {NVDA:{name:'NVIDIA',price:142.87,sector:'Technology'},AAPL:{name:'Apple',price:228.42,sector:'Consumer electronics'},MSFT:{name:'Microsoft',price:418.79,sector:'Software'}};
let current = {symbol:'NVDA',date:'2026-09-09',provider:'Codex',depth:'1',analysts:['market','fundamentals','news','sentiment']};
let history = [current,{...current,symbol:'AAPL',date:'2026-09-08'},{...current,symbol:'MSFT',date:'2026-09-08'}];
let running = false, timer, activeTab = 'market', period = '1M';
const stages = ['전문가 분석','리서치 토론','트레이더 전략','리스크 검토','최종 판단'];
const subtitles = ['Analyst team','Bull & bear debate','Trading strategy','Risk management','Portfolio manager'];
const reports = {
 market:{name:'Market Analyst',title:'완만한 상승 흐름',body:'샘플 차트에서 가격은 50일 이동평균 위에 위치하며, 단기 추세는 완만한 상승 흐름을 보입니다. RSI는 과열 구간에 진입하지 않은 중립 영역으로 설정했습니다. 거래량이 추세를 뒷받침하는지 추가 확인이 필요합니다.',insight:'추세의 지속성과 거래량 확인',detail:'가격 방향만으로 판단하기보다 거래량과 모멘텀 지표를 함께 확인하는 분석 예시입니다.'},
 fundamentals:{name:'Fundamentals Analyst',title:'실적 확인 필요',body:'매출 성장, 영업이익률, 현금흐름을 함께 검토하는 리포트 영역입니다. 이 예시에서는 성장 기대와 밸류에이션 부담이 공존하는 상황을 가정합니다. 실제 연결 시 분석 기준일까지 공개된 재무자료를 바탕으로 근거를 표시합니다.',insight:'성장성과 가격의 균형',detail:'예상 성장률이 현재 가격에 얼마나 반영되어 있는지 검토합니다.'},
 news:{name:'News Analyst',title:'이벤트 관찰',body:'산업 수요, 기업 발표, 거시경제 이벤트를 종합하는 예시 리포트입니다. 새로운 투자 계획은 기대를 높일 수 있지만 정책과 금리 변화가 불확실성을 만들 수 있습니다. 이 프로토타입에는 실제 뉴스 기사나 실시간 데이터가 연결되어 있지 않습니다.',insight:'이벤트 전후의 불확실성',detail:'실제 보고서에서는 기사 출처와 발표 시점을 확인할 수 있도록 구현할 예정입니다.'},
 sentiment:{name:'Sentiment Analyst',title:'혼합된 심리',body:'시장 참여자의 낙관과 경계가 함께 나타나는 가상 시나리오입니다. 긍정적인 언급이 늘어도 실적 개선과 같은 의미로 해석하지 않습니다. 뉴스와 커뮤니티의 관점을 구분하고, 표본의 편향을 함께 검토하는 화면입니다.',insight:'관심과 기업 가치는 별개의 신호',detail:'심리 지표를 단독 판단 근거로 쓰지 않고 다른 분석가의 결과와 함께 비교합니다.'}
};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function showView(view){['research','history','settings'].forEach(v=>$('#'+v+'View').hidden=v!==view);$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={research:'리서치 스튜디오',history:'분석 기록',settings:'모델 및 설정'};$('#breadcrumb').textContent=titles[view];$('#pageTitle').textContent=titles[view];$('#pageDescription').textContent=view==='research'?'시장을 읽는 다양한 관점. 하나의 명확한 리서치.':view==='history'?'이전 리서치의 근거와 판단을 다시 살펴보세요.':'분석가와 리서치 팀이 사용할 모델을 구성하세요.'}
function renderHistory(){ $('#recent').replaceChildren();$('#historyList').replaceChildren();history.forEach((r,i)=>{const b=document.createElement('button');b.className='recent-button';b.innerHTML=`<span class="recent-icon">${r.symbol[0]}</span><div>${r.symbol}<small>${r.date.replaceAll('-','.')} · 샘플</small></div><span>↗</span>`;b.onclick=()=>openRecord(i);if(i<4)$('#recent').append(b);const row=document.createElement('button');row.className='history-row';row.innerHTML=`<span class="recent-icon">${r.symbol[0]}</span><strong>${stocks[r.symbol].name}</strong><span>${r.symbol}</span><span>${r.date}</span><span>${r.provider}</span><span>샘플 보고서 →</span>`;row.onclick=()=>openRecord(i);$('#historyList').append(row)});$('#historyCount').textContent=history.length}
function openRecord(i){if(running)return toast('시뮬레이션 완료 후 다른 기록을 확인할 수 있습니다.');current={...history[i]};renderResearch();showView('research')}
function renderStages(progress=5){$('#pipeline').innerHTML=stages.map((s,i)=>`<div class="step ${i>progress?'wait':i===progress?'running':''}"><span class="step-number">${i<progress?'✓':String(i+1).padStart(2,'0')}</span><div><strong>${s}</strong><small>${subtitles[i]}</small></div></div>`).join('');$('#activity').innerHTML=stages.slice(0,Math.min(progress+1,5)).map((s,i)=>`<div class="activity-item"><span class="activity-check">${i<progress?'✓':'◌'}</span><div><strong>${s} ${i<progress?'완료':'진행 중'}</strong><small>${i===0?current.analysts.length+'명의 분석가':subtitles[i]} · ${current.provider} · 예시</small></div><time>${i<progress?'완료':'실행 중'}</time></div>`).join('')}
function renderChart(){const seed={NVDA:1,AAPL:2,MSFT:3}[current.symbol]+{ '1W':0,'1M':2,'3M':4}[period];const points=Array.from({length:65},(_,i)=>[i*10.6,145-i*1.5+Math.sin(i*1.3+seed)*10+Math.sin(i*.4+seed)*15]);const line=points.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');$('#chart').innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="var(--chart-fill)" stop-opacity=".22"/><stop offset="1" stop-color="var(--chart-fill)" stop-opacity="0"/></linearGradient></defs>${[20,65,110,155].map((y,i)=>`<line x1="0" y1="${y}" x2="690" y2="${y}" stroke="#eef1f3" stroke-dasharray="3 5"/><text x="710" y="${y+3}" fill="#a6adb7" font-size="10">${(stocks[current.symbol].price+10-i*10).toFixed(0)}</text>`).join('')}<path d="${line} L678.4,180 L0,180 Z" fill="url(#fill)"/><path d="${line}" fill="none" stroke="var(--chart-line)" stroke-width="2" stroke-linejoin="round"/><circle cx="${points.at(-1)[0]}" cy="${points.at(-1)[1]}" r="4" fill="var(--chart-line)" stroke="var(--surface)" stroke-width="2"/>`;const end=new Date(current.date+'T12:00:00');const span={'1W':7,'1M':30,'3M':90}[period];$('#chartLabels').innerHTML=Array.from({length:5},(_,i)=>{const d=new Date(end);d.setDate(d.getDate()-Math.round(span*(1-i/4)));return `<span>${d.getMonth()+1}월 ${d.getDate()}일</span>`}).join('');const pct={'1W':1.82,'1M':6.26,'3M':12.48}[period];$('#priceChange').textContent=`↗ +${(stocks[current.symbol].price*pct/(100+pct)).toFixed(2)} (${pct}%)`;}
function renderReport(){const r=reports[activeTab];$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===activeTab);b.setAttribute('aria-selected',b.dataset.tab===activeTab);b.disabled=running||!current.analysts.includes(b.dataset.tab)});$('#reportContent').innerHTML=`<div class="analyst-heading"><span class="analyst-avatar" aria-hidden="true">${icon("chart")}</span><div><strong>${r.name}</strong><small>${current.provider} · 예시 리포트</small></div><span class="pill green">${r.title}</span></div><p class="report-text">${r.body}</p><div class="insight"><strong>핵심 인사이트 · ${r.insight}</strong>${r.detail}</div><div class="report-bottom"><span>예시 리포트 · ${current.symbol}</span><span>분석 기준 ${current.date}</span></div>`}
function renderResearch(){const s=stocks[current.symbol];$('#stockName').textContent=s.name;$('#ticker').textContent=current.symbol;$('#stockLogo').textContent=current.symbol[0];$('#stockMeta').textContent=`NASDAQ · ${s.sector} · USD`;$('#price').textContent='$'+s.price.toFixed(2);$('#analysisDate').textContent=current.date.replaceAll('-','.');if(!current.analysts.includes(activeTab))activeTab=current.analysts[0];renderChart();renderReport();renderStages();$('.report-card .muted').textContent=current.analysts.length+'명의 분석가';$('.debate-card .sample').textContent=`토론 예시 · ${current.depth} 라운드`;const isNvda=current.symbol==='NVDA';$('.debate-grid h4').textContent=isNvda?'성장을 뒷받침하는 수요':'성장 기회와 사업 경쟁력';$('.debate-grid p').textContent=isNvda?'AI 인프라 투자가 이어진다는 가정 아래, 데이터센터 부문의 성장과 견고한 수익성에 주목합니다.':'주력 사업의 수요가 유지된다는 가정 아래, 제품 경쟁력과 현금 창출력을 긍정적으로 평가하는 토론 예시입니다.'}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;renderReport()});
$$('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;$$('[data-period]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});renderChart()});
$('#newAnalysis').onclick=()=>{if(running)return;$('#formError').textContent='';$('#analysisDialog').showModal()};
$('#closeDialog').onclick=()=>$('#analysisDialog').close();
$('#saveSettings').onclick=()=>{if(!$('#quickModel').value.trim()||!$('#deepModel').value.trim())return toast('모델 이름을 입력해주세요.');$('#provider').value=$('#settingsProvider').value;toast('새 분석에 사용할 예시 설정을 적용했습니다.')};
$('#analysisForm').onsubmit=async(e)=>{e.preventDefault();const analysts=$$('input[name="analyst"]:checked').map(b=>b.value);if(!analysts.length){$('#formError').textContent='분석가를 한 명 이상 선택해주세요.';return}current={symbol:$('#symbol').value,date:$('#date').value,provider:$('#provider').value,depth:$('#depth').value,analysts,quickModel:$('#quickModel').value,deepModel:$('#deepModel').value};$('#analysisDialog').close();running=true;$('#newAnalysis').disabled=true;renderResearch();showView('research');$('.decision-rating').innerHTML='··· <span>판단 생성 중</span>';$('.decision-card>p').textContent='분석가와 리서치 팀의 예시 흐름을 재생하고 있습니다.';$('#download').disabled=true;$('.report-card').hidden=true;$('.debate-card').hidden=true;$('#runStatus').textContent='◌ 시뮬레이션 중';$('#activitySummary').textContent='예시 분석 진행 중';for(let i=0;i<5;i++){renderStages(i);$('#elapsed').textContent=`00:0${i*2}`;await new Promise(resolve=>setTimeout(resolve,1800))}running=false;$('#newAnalysis').disabled=false;$('#download').disabled=false;$('.report-card').hidden=false;$('.debate-card').hidden=false;$('.decision-rating').innerHTML='BUY <span>매수 의견</span>';$('.decision-card>p').innerHTML='성장 모멘텀은 긍정적입니다.<br>가격 부담을 고려한 분할 접근을 제안합니다.';$('#runStatus').textContent='✓ 분석 완료';$('#activitySummary').textContent='모든 단계 완료';$('#elapsed').textContent='00:09';history.unshift({...current});renderResearch();renderHistory();toast('예시 분석이 완료되었습니다. 각 분석가의 보고서를 확인하세요.')};
$('#download').onclick=()=>{const content=`# ${current.symbol} 리서치 — 프로토타입 샘플\n\n실제 금융 데이터나 모델 분석이 아닙니다.\n\n기준일: ${current.date}\n제공자: ${current.provider}\n빠른 모델: ${current.quickModel||'default'}\n심층 모델: ${current.deepModel||'default'}\n토론: ${current.depth} 라운드\n\n${current.analysts.map(a=>`## ${reports[a].name}\n${reports[a].body}\n\n${reports[a].detail}`).join('\n\n')}\n\n## 최종 판단 (예시)\nBUY — 성장 모멘텀과 가격 부담을 함께 고려한 분할 접근.\n\n이 파일은 UI 프로토타입에서 생성한 샘플이며 실제 투자 분석 결과가 아닙니다.\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${current.symbol}-${current.date}-sample.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('샘플 보고서를 다운로드했습니다.')};
renderResearch();renderHistory();
// Keep segmented report navigation usable without a pointer.
$('.tabs').addEventListener('keydown', event => {
  if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
  const tabs = $$('[data-tab]').filter(button => !button.disabled);
  const index = tabs.indexOf(document.activeElement);
  if (index < 0 || !tabs.length) return;
  event.preventDefault();
  const next = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1
    : (index + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length;
  tabs[next].focus();
  tabs[next].click();
});
